using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using ShowMeTheMoney.API.Models;

namespace ShowMeTheMoney.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class TransactionsController : ControllerBase
{
    private readonly IWebHostEnvironment _env;

    public TransactionsController(IWebHostEnvironment env)
    {
        _env = env;
    }

    [HttpGet]
    public async Task<IActionResult> GetTransactions()
    {
        // In a real app, this would come from a database.
        // Here we read from the mock file generated by the script.
        // Assuming the script runs in the root and outputs to the root or scripts folder.
        // Let's look for it in the project root or a known location.
        
        // We will assume the mock file is copied to the output directory or we read it from a fixed path.
        // For simplicity, let's try to read from the project root's parent scripts folder or just hardcode the path for now relative to the execution.
        
        // Better approach: The script generated "mock_transactions.json" in the root of the workspace (C:\dev\ProjectShowMeTheMoney\mock_transactions.json)
        // because I ran it from C:\dev\ProjectShowMeTheMoney.
        
        string filePath = Path.Combine(_env.ContentRootPath, "..", "mock_transactions.json");
        
        if (!System.IO.File.Exists(filePath))
        {
            return NotFound("Mock data file not found. Please run the generation script.");
        }

        string jsonString = await System.IO.File.ReadAllTextAsync(filePath);
        
        // We can deserialize to validate or just return the raw JSON.
        // Let's deserialize to ensure it matches our model, then return.
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };
        
        try 
        {
            var transactionData = JsonSerializer.Deserialize<TransactionResponse>(jsonString, options);
            return Ok(transactionData);
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Error parsing mock data: {ex.Message}");
        }
    }
}
